name: course_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - discretize=0.11.2
  - matplotlib=3.10.0
  - netcdf4=1.7.2
  - numpy=2.2.2
  - pandas=2.2.3
  - rasterio=1.4.3
  - scipy=1.15.1
  - simpeg=0.23.0
  - xarray
  - pyproj
  - cmocean
  - verde
  - harmonica
  - IPython.display
  - discretize
  - simpeg
  - choclo
  
